# Generated by Django 4.2 on 2023-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=36)),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
